name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: owt-cluster
  GKE_ZONE: asia-southeast1
  DEPLOYMENT_NAME: frontend-deployment
  REGISTRY: asia-northeast3-docker.pkg.dev
  REPOSITORY: frontend-images
  IMAGE: login-vite-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-northeast3-docker.pkg.dev/$PROJECT_ID/frontend-images/login-vite-frontend:$GITHUB_SHA \
                     -t asia-northeast3-docker.pkg.dev/$PROJECT_ID/frontend-images/login-vite-frontend:latest .

    - name: Push to Artifact Registry
      run: |
        docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/frontend-images/login-vite-frontend:$GITHUB_SHA
        docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/frontend-images/login-vite-frontend:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/$DEPLOYMENT_NAME \
          frontend-container=asia-northeast3-docker.pkg.dev/$PROJECT_ID/frontend-images/login-vite-frontend:$GITHUB_SHA
        kubectl rollout status deployment/$DEPLOYMENT_NAME